# Generated by Django 5.2.3 on 2025-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
